sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
bundler_args: --jobs 3 --retry 3
branches:
  only:
    - master

# this avoids build issues with rainbow on old bundler/rubygems
before_install:
  - gem update --system
  - gem --version
  - gem uninstall bundler -a -x -I
  - rvm @global do gem uninstall bundler -a -x -I
  - gem install bundler
  - bundle --version
  - rm -f .bundle/config
